---
output: html_document
editor_options: 
  chunk_output_type: console
chunk_output_type: console
---
Mackenzie Adams and Henry Scott

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```

Install and load needed packages

```{r}
library(dataRetrieval)
library(tidyverse)
library(dplyr)
library(patchwork)
library(zoo)
library(daymetr) 
library(leaflet) 
library(fs)
library(ggpubr) # for adding R and P vals to graphs
library(DescTools) # for doing Mode statistical calc
library(rstatix)
library(midasr)
library(ggiraphExtra)
library(circlize)
library(ggpmisc)
library(grid)
library(gridExtra)
library(gganimate)
```

```{r}
# USGS GAGE INFO/DATA 

# This efficiently automates the process of getting all the stream data desired into one df.

gage_ids <- 
  tribble(
    ~site_name,        ~site_no,
    "Dungeness_River",  "12048000",
    "Elwha_River",      "12045500",
    "Skokomish_River",  "12061500")

# set all the parameters
start <- date("1982-10-01")
end <- date("2023-9-30")
para <-c("00060", "00065")

# if sites in gage_ids are changed, uncomment the code below and run it once. This stores the data locally and eventually in the repo if its pushed. This is mostly to be polite to the USGS hosting service.

# NWIS_data <- readNWISdv(gage_ids$site_no, para, start, end)
# saveRDS(NWIS_data, "NWIS_data.rdata")
# 
# NWIS_meta <- readNWISsite(gage_ids$site_no)
# saveRDS(NWIS_meta, "NWIS_meta.rdata")

gage_ids <- 
  readRDS("NWIS_meta.rdata") %>% 
  select(site_no,
         dec_lat_va, 
         dec_long_va) %>%
  inner_join(gage_ids, .)

gage_data <-
  readRDS("NWIS_data.rdata") %>%
  inner_join(gage_ids, .) %>% 
  renameNWISColumns() %>%
  drop_na(Flow) %>%
  mutate(water_year = calcWaterYear(Date)) %>%
  group_by(site_name, site_no)

gage_data %>%
  group_by(site_name) %>%
  summarise(n = n())

# Shows all unique grouped elements in gage_data. Verifies that all the desired gages were selected and are in the data frame.

summarize(gage_data)

```


```{r}
# WEATHER DATA ACQUISITION: This code retrieves the desired precipitation and temperature data.

# write_csv(x = select(gage_ids, -"site_no"), file = "gage_ids.csv")
# 
# daymet_all <- download_daymet_batch(file_location = "./gage_ids.csv", start = year(start), end = year(end), internal = T, simplify = F)
# saveRDS(daymet_all, "DAYMET_all.rdata")


# Downloading data works. Now to append it...

daymet_reorg <-
  function(f) {
    bind_cols(data = f$data, site = f$site, .name_repair = "unique")
  } 

gage_data_all <- 
  lapply(readRDS("./DAYMET_all.rdata"), daymet_reorg) %>%
  bind_rows() %>%
  rename(doy = yday, 
         ann = year,
         prcp_daily_mm = prcp..mm.day.,
         t_max_C = tmax..deg.c.,
         t_min_C = tmin..deg.c.) %>%
  mutate(
    Date = make_datetime(year = ann, day = doy),
    t_avg_C = (t_max_C + t_min_C)/2) %>%
  select(site,
         Date,
         prcp_daily_mm,
         t_max_C,
         t_min_C,
         t_avg_C,
         ann
  ) %>%
  left_join(ungroup(gage_data), ., join_by(site_name == site, Date == Date)) %>%
  drop_na(t_min_C)

#Now the discharge, precipitation, and temperature data is all in one data frame.
```

#DO WE NEED ALL OF THIS CODE? IS SOME OF IT A REPEAT OF MY NEW OFFSET DATA CODE?
```{r}
# ADD FISH DATA: This code reads in csv files containing salmon return data downloaded for the particular rivers of interest from the stateofsalmon.wa.gov site.

fish_files <-
  dir_ls("./Salmon_Data/")


# creates a df of fish data. Originally, the code 1 chunk below this did this within its own workflow but I made it a seperate df bc i need it somewhere else, not attached to climate data
fish_data <-
  fish_files %>%
  lapply(read_csv) %>%
  bind_rows() %>%
  filter(data_type == "TSAEJ") %>%
  
  # this line moves the allignment of the fish data by a year bc supposedly that makes things line up better. Its like 11:30 and im tired and i dont trust myself to solve dates
  mutate(site_name = paste0(str_extract(population_name, "^\\w+"), "_River"), .before = "stock_number") %>% 
  select(abundance_qty,
         year,
         site_name) %>%
  drop_na(abundance_qty)

gage_fish_all <-
  fish_files %>%
  lapply(read_csv) %>%
  bind_rows() %>%
  filter(data_type == "TSAEJ") %>%
  mutate(site_name = paste0(str_extract(population_name, "^\\w+"), "_River"), .before = "stock_number") %>% 
  select(abundance_qty,
         year,
         site_name) %>%
  drop_na(abundance_qty) %>%
  left_join(gage_data_all,., by = c(
    "water_year" = "year",
    "site_name" = "site_name"
  )
  )

```


```{r}
#Offsetting the climate data by four years (ex. salmon returns that occurred during 1990's water year are now dependent on 1986 climate data) and assigning the salmon return values to change at each new water year.

gage_fish_lead_2 <- gage_fish_all %>%
  mutate(Date = as.Date(Date))
  

env_data <- gage_fish_all %>%
 filter(year(Date) >= 1982 & year(Date) <= 2023) %>%
 select(site_name, Date, prcp_daily_mm, Flow, t_max_C, t_min_C, t_avg_C)

env_data <- env_data %>% 
  mutate(Date = Date + years (4))

abundance_data <- gage_data_all %>%
  filter(year(Date) >= 1986 & year(Date) <= 2023) %>%
  select(site_name, Date) 


aligned_data <- 
  abundance_data %>%
  left_join(env_data, by = c("site_name", "Date")) %>%
  addWaterYear() %>%
  left_join(., fish_data, by = c(
    "site_name" = "site_name",
    "waterYear" = "year"))

aligned_data_clean <- 
  aligned_data %>%
  mutate(site_name = recode(site_name,
                            "Elwha_River" = "Elwha River",
                            "Dungeness_River" = "Dungeness River",
                            "Skokomish_River" = "Skokomish River"))


```


```{r}
#This code produces a figure that shows years on the x axis and discharge on the y-axis for the three rivers of interest. The Dungeness River produces substantially less discharge compared to the Elwha and the Skokomish, therefore we set the boundaries for all three to be "free" so that patterns in discharge can more easily be examined and the data fills up the whole graph area.

q_gg <-
  aligned_data_clean %>%
  ggplot(aes(x = Date, y = Flow, color = site_name)) +
  geom_line() + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Discharge (cfs)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none", )

#Shows river discharge over time for the Skokomish.
q_gg_Skokomish <-
  aligned_data_clean %>%
  filter(site_name == "Skokomish River") %>%
  ggplot(aes(x = Date, y = Flow)) +
  geom_line(color = "dodgerblue") + 
  theme_minimal() +
  labs( x = "Year", y = "Discharge (cfs)", title = "Skokomish River") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",
        plot.title = element_text(hjust = 0.5))

#Shows river discharge over time for the Dungeness.
q_gg_Dungeness <-
  aligned_data_clean %>%
  filter(site_name == "Dungeness River") %>%
  ggplot(aes(x = Date, y = Flow)) +
  geom_line() + 
  theme_minimal() +
  labs( x = "Year", y = "Discharge (cfs)", title = "Dungeness River") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none", 
        plot.title = element_text(hjust = 0.5))

#Shows river discharge over time for the Elwha.
q_gg_Elwha <-
  aligned_data_clean %>%
  filter(site_name == "Elwha River") %>%
  ggplot(aes(x = Date, y = Flow)) +
  geom_line(color = "limegreen") + 
  theme_minimal() +
  labs( x = "Year", y = "Discharge (cfs)", title = "Elwha River") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none", 
        plot.title = element_text(hjust = 0.5))
```


```{r}
#This code generates a plot with year on the x-axis and precipitation(mm) on the y-axis for the areas where the three streams of interest are located.

prcp_gg <-
  aligned_data_clean %>%
  ggplot(aes(x = Date, y = prcp_daily_mm, color = site_name)) +
  geom_line() + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Precipitation (mm)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

#Plot of precipitation over the years for the Elwha. 
prcp_gg_Elwha <-
  aligned_data_clean %>%
  filter(site_name == "Elwha River") %>%
  ggplot(aes(x = Date, y = prcp_daily_mm, color = site_name)) +
  geom_line(color = "limegreen") + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Precipitation (mm)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

#Plot of precipitation over the years for the Dungeness.
prcp_gg_Dungeness <-
  aligned_data_clean %>%
  filter(site_name == "Dungeness River") %>%
  ggplot(aes(x = Date, y = prcp_daily_mm, color = site_name)) +
  geom_line() + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Precipitation (mm)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

#Plot of precipitation over the years for the Skokomish. 
prcp_gg_Skokomish <-
  aligned_data_clean %>%
  filter(site_name == "Skokomish River") %>%
  ggplot(aes(x = Date, y = prcp_daily_mm, color = site_name)) +
  geom_line(color = "dodgerblue") + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Precipitation (mm)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

```


```{r}
#This code generates a plot with year on the x-axis and average temperature(C) on the y-axis for the areas where the three streams of interest are located.

temp_gg <-
  aligned_data_clean %>%
  ggplot(aes(x = Date, y = t_avg_C, color = site_name)) +
  geom_line() + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Temperature (C)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

#Plot of precipitation over the years for the Elwha. 

temp_gg_Dungeness <-
  aligned_data_clean %>%
  filter(site_name == "Dungeness River") %>%
  ggplot(aes(x = Date, y = t_avg_C, color = site_name)) +
  geom_line() + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Temperature (C)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

#Plot of precipitation over the years for the Elwha. 

temp_gg_Elwha <-
  aligned_data_clean %>%
  filter(site_name == "Elwha River") %>%
  ggplot(aes(x = Date, y = t_avg_C, color = site_name)) +
  geom_line(color = "limegreen") + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Temperature (C)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

#Plot of precipitation over the years for the Skokomish. 
temp_gg_Skokomish <-
  aligned_data_clean %>%
  filter(site_name == "Skokomish River") %>%
  ggplot(aes(x = Date, y = t_avg_C, color = site_name)) +
  geom_line(color = "dodgerblue") + 
  theme_minimal() +
  facet_wrap(~ gsub("_", " ", site_name), nrow = 3, scales = "free") +
  labs( x = "Year", y = "Temperature (C)", color = "Gage") +
  theme(strip.text = element_text(size = 12), 
        axis.title.x = element_text(size = 14), 
        axis.title.y = element_text(size = 14), 
        legend.position = "none",)

```


```{r}
#Line graphs with updated data set. 

#Returns over time of all three rivers on one graph.
aligned_data_clean %>%
  ggplot(aes(x = waterYear, y = abundance_qty, color = site_name)) +
  geom_line() +
  geom_point() + 
  theme_classic() +
  labs(
    title = "Salmon Abundance Over Time",
    color = "Site",
    y = "Salmon Return Abundance",
    x = "Year") + 
  theme(axis.title = element_text(size = 12), axis.text = element_text(size = 12))


#Returns in each seperate river on seperate graphs stacked together.
aligned_data_clean %>%
  ggplot(aes(x = waterYear, y = abundance_qty, color = site_name)) +
  geom_line() +
  geom_point() +
  theme_classic() +
  labs(title = "Salmon Abundance Over Time",
       color = "Site",
       y = "Salmon Return Abundance",
       x = "Year") +
  facet_wrap(~ site_name, scales = "free_y", ncol = 1) + 
  theme(axis.title = element_text(size = 12),
axis.text = element_text(size = 12))


#Salmon returns over the years in the Skokomish
SkokomishReturns <-
  aligned_data_clean %>%
  filter(site_name == "Skokomish River") %>%
  ggplot(aes(x = waterYear, y = abundance_qty, color = site_name)) +
  geom_line(color = "dodgerblue") +
  geom_point(color = "dodgerblue") +
  theme_classic() +
  labs(
       color = "Site",
       y = "Salmon Return Abundance",
       x = "") +
  theme(axis.title = element_text(size = 12),
axis.text = element_text(size = 12))


#Salmon returns over the years in the Elwha
ElwhaReturns <-
  aligned_data_clean %>%
  filter(site_name == "Elwha River") %>%
  ggplot(aes(x = waterYear, y = abundance_qty, color = site_name)) +
  geom_line(color = "limegreen") +
  geom_point(color = "limegreen") +
  theme_classic() +
  labs(
       color = "Site",
       y = "Salmon Return Abundance",
       x = "") +
  theme(axis.title = element_text(size = 12),
axis.text = element_text(size = 12))

#Salmon returns over the years in the Dungeness
DungenessReturns <-
  aligned_data_clean %>%
  filter(site_name == "Dungeness River") %>%
  ggplot(aes(x = waterYear, y = abundance_qty, color = site_name)) +
  geom_line(color = "salmon") +
  geom_point(color = "salmon") +
  theme_classic() +
  labs(
       color = "Site",
       y = "Salmon Return Abundance",
       x = "") +
  theme(axis.title = element_text(size = 12),
axis.text = element_text(size = 12))

```


```{r}
#This code places the three above graphs side by side so that trends between the three rivers can easily be examined.

q_gg + prcp_gg + temp_gg

q_gg +prcp_gg 

prcp_gg + temp_gg

q_gg + temp_gg


SkokomishReturns + q_gg_Skokomish + prcp_gg_Skokomish + temp_gg_Skokomish 

DungenessReturns + q_gg_Dungeness + prcp_gg_Dungeness + temp_gg_Dungeness 

ElwhaReturns + q_gg_Elwha + prcp_gg_Elwha + temp_gg_Elwha

```


```{r}
#Creates a chart using the new data set with two y axis, legend, colors, etc. of Date vs Flow vs Salmon returns

DischargeandReturns_2 <-
  aligned_data %>%
  filter(Date < "2023-10-01") %>%
  ggplot() +
  geom_line(aes(x = Date, y = Flow, color = site_name)) +
  facet_wrap(~ site_name, 
             nrow = 3, 
             scales = "free") +
  geom_point(data = annual_salmon_returns_2, 
             aes(x = as.POSIXct(ann), 
                 y = abundance_qty), 
             color = "black", 
             size = .75) + 
  scale_y_continuous(name = "Flow (cfs)", sec.axis = sec_axis(~ ., name = "Salmon Return Abundance")) + 
  theme_minimal() +
  theme(
 axis.title.y.right = element_text(color = "black"),
 legend.position = "bottom", # Position legend at the bottom
 legend.title = element_text(face = "bold") # Bold legend title
 ) +
 labs(color = "Site Name")

```

```{r}
#This code creates some stats about our aligned data.

aligned_data_stats <-
  aligned_data %>%
  filter(waterYear != 1986) %>%
  mutate(site_name = case_when(
    site_name == "Dungeness_River" ~ "Dungeness River",
    site_name == "Elwha_River" ~ "Elwha River",
    site_name == "Skokomish_River" ~ "Skokomish River",
    TRUE ~ site_name
  )) %>%
  group_by(site_name, waterYear) %>%
  reframe(
    abundance_qty = Mode(abundance_qty),
    Flow_median = median(Flow, na.rm = TRUE),
    Flow_max = max(Flow, na.rm = TRUE),
    Flow_min = min(Flow, na.rm = TRUE),
    t_ann_median = median(t_avg_C, na.rm = TRUE),
    t_ann_min = min(t_avg_C, na.rm = TRUE),
    t_ann_max = max(t_avg_C, na.rm = TRUE),
    prcp_median = median(prcp_daily_mm, na.rm = TRUE),
    prcp_max = max(prcp_daily_mm, na.rm = TRUE),
    prcp_min = min(prcp_daily_mm, na.rm = TRUE)
  )

```

```{r}
#Creating three separate graphs of the Median Q values across the time series for the three rivers of interest. 

DungenessMedianQ <-
aligned_data_stats %>%
 filter(site_name == "Dungeness River") %>%
 ggplot(aes(x = waterYear, y = Flow_median, color = site_name)) +
 geom_line(show.legend = FALSE) +
 geom_point(show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Median Discharge (cfs)",
 x = "Year") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))


ElwhaMedianQ <-
aligned_data_stats %>%
 filter(site_name == "Elwha River") %>%
 ggplot(aes(x = waterYear, y = Flow_median, color = site_name)) +
 geom_line(color = "limegreen", show.legend = FALSE) +
 geom_point(color = "limegreen", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Median Discharge (cfs)",
 x = "Year") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

SkokomishMedianQ <-
aligned_data_stats %>%
 filter(site_name == "Skokomish River") %>%
 ggplot(aes(x = waterYear, y = Flow_median, color = site_name)) +
 geom_line(color = "dodgerblue", show.legend = FALSE) +
 geom_point(color = "dodgerblue", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Median Discharge (cfs)",
 x = "Year") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))
 

#Creating three separate graphs of the MaxQ values across the time series for the three rivers of interest. 

DungenessMaxQ <-
aligned_data_stats %>%
 filter(site_name == "Dungeness River") %>%
 ggplot(aes(x = waterYear, y = Flow_max, color = site_name)) +
 geom_line(show.legend = FALSE) +
 geom_point(show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Max Discharge (cfs)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

ElwhaMaxQ <-
aligned_data_stats %>%
 filter(site_name == "Elwha River") %>%
 ggplot(aes(x = waterYear, y = Flow_max, color = site_name)) +
 geom_line(color = "limegreen", show.legend = FALSE) +
 geom_point(color = "limegreen", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Max Discharge (cfs)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

SkokomishMaxQ <-
aligned_data_stats %>%
 filter(site_name == "Skokomish River") %>%
 ggplot(aes(x = waterYear, y = Flow_max, color = site_name)) +
 geom_line(color = "dodgerblue", show.legend = FALSE) +
 geom_point(color = "dodgerblue", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Max Discharge (cfs)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

#Creating three separate graphs of the Minimum Q values across the time series for the three rivers of interest.

DungenessMinQ <-
aligned_data_stats %>%
 filter(site_name == "Dungeness River") %>%
 ggplot(aes(x = waterYear, y = Flow_min, color = site_name)) +
 geom_line(show.legend = FALSE) +
 geom_point(show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Minimum Discharge (cfs)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

ElwhaMinQ <-
aligned_data_stats %>%
 filter(site_name == "Elwha River") %>%
 ggplot(aes(x = waterYear, y = Flow_min, color = site_name)) +
 geom_line(color = "limegreen", show.legend = FALSE) +
 geom_point(color = "limegreen", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Minimum Discharge (cfs)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

SkokomishMinQ <-
aligned_data_stats %>%
 filter(site_name == "Skokomish River") %>%
 ggplot(aes(x = waterYear, y = Flow_min, color = site_name)) +
 geom_line(color = "dodgerblue", show.legend = FALSE) +
 geom_point(color = "dodgerblue", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Minimum Discharge (cfs)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

#stacking the graphs 

SkokomishDischarge <- grid.arrange(SkokomishMinQ, SkokomishMaxQ, SkokomishMedianQ, ncol = 1, top = textGrob("Skokomish River Discharge Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

ElwhaDischarge <- grid.arrange(ElwhaMinQ, ElwhaMaxQ, ElwhaMedianQ, ncol = 1, top = textGrob("Elwha River Discharge Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

DungenessDischarge <- grid.arrange(DungenessMinQ, DungenessMaxQ, DungenessMedianQ, ncol = 1, top = textGrob("Dungeness River Discharge Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

#stacking these with salmon graphs

SkokomishTrends <- grid.arrange(SkokomishReturns, SkokomishMinQ, SkokomishMaxQ, SkokomishMedianQ, ncol = 1, top = textGrob("Skokomish Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

DungenessTrends <- grid.arrange(DungenessReturns, DungenessMinQ, DungenessMaxQ, DungenessMedianQ, ncol = 1, top = textGrob("Dungeness Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

ElwhaTrends <- grid.arrange(ElwhaReturns, ElwhaMinQ, ElwhaMaxQ, ElwhaMedianQ, ncol = 1, top = textGrob("Elwha Analysis", gp = gpar(fontsize = 16, fontface = "bold")))


```

```{r}
#Creating three separate graphs of the Median Temp values across the time series for the three rivers of interest. 

DungenessMedianTemp <-
aligned_data_stats %>%
 filter(site_name == "Dungeness River") %>%
 ggplot(aes(x = waterYear, y = t_ann_median, color = site_name)) +
 geom_line(show.legend = FALSE) +
 geom_point(show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Median Temperature (C)",
 x = "Year") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))


ElwhaMedianTemp <-
aligned_data_stats %>%
 filter(site_name == "Elwha River") %>%
 ggplot(aes(x = waterYear, y = t_ann_median, color = site_name)) +
 geom_line(color = "limegreen", show.legend = FALSE) +
 geom_point(color = "limegreen", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Median Temperature (C)",
 x = "Year") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

SkokomishMedianTemp <-
aligned_data_stats %>%
 filter(site_name == "Skokomish River") %>%
 ggplot(aes(x = waterYear, y = t_ann_median, color = site_name)) +
 geom_line(color = "dodgerblue", show.legend = FALSE) +
 geom_point(color = "dodgerblue", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Median Temperature (C)",
 x = "Year") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))
 

#Creating three separate graphs of the Max Temperature values across the time series for the three rivers of interest. 

DungenessMaxTemp <-
aligned_data_stats %>%
 filter(site_name == "Dungeness River") %>%
 ggplot(aes(x = waterYear, y = t_ann_max, color = site_name)) +
 geom_line(show.legend = FALSE) +
 geom_point(show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Max Temperature (C)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

ElwhaMaxTemp <-
aligned_data_stats %>%
 filter(site_name == "Elwha River") %>%
 ggplot(aes(x = waterYear, y = t_ann_max, color = site_name)) +
 geom_line(color = "limegreen", show.legend = FALSE) +
 geom_point(color = "limegreen", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Max Temperature (C)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

SkokomishMaxTemp <-
aligned_data_stats %>%
 filter(site_name == "Skokomish River") %>%
 ggplot(aes(x = waterYear, y = t_ann_max, color = site_name)) +
 geom_line(color = "dodgerblue", show.legend = FALSE) +
 geom_point(color = "dodgerblue", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Max Temperature (C)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

#Creating three separate graphs of the Minimum Q values across the time series for the three rivers of interest.

DungenessMinTemp <-
aligned_data_stats %>%
 filter(site_name == "Dungeness River") %>%
 ggplot(aes(x = waterYear, y = t_ann_min, color = site_name)) +
 geom_line(show.legend = FALSE) +
 geom_point(show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Minimum Temperature (C)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

ElwhaMinTemp <-
aligned_data_stats %>%
 filter(site_name == "Elwha River") %>%
 ggplot(aes(x = waterYear, y = t_ann_min, color = site_name)) +
 geom_line(color = "limegreen", show.legend = FALSE) +
 geom_point(color = "limegreen", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Minimum Temperature (C)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

SkokomishMinTemp <-
aligned_data_stats %>%
 filter(site_name == "Skokomish River") %>%
 ggplot(aes(x = waterYear, y = t_ann_min, color = site_name)) +
 geom_line(color = "dodgerblue", show.legend = FALSE) +
 geom_point(color = "dodgerblue", show.legend = FALSE) +
 theme_classic() +
 labs(color = "Site",
 y = "Minimum Temperature (C)",
 x = "") + theme(axis.title = element_text(size = 12),
 axis.text = element_text(size = 12))

#stacking the graphs 

SkokomishTemperature <- grid.arrange(SkokomishMinTemp, SkokomishMaxTemp, SkokomishMedianTemp, ncol = 1, top = textGrob("Skokomish River Temperature Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

ElwhaTemperature <- grid.arrange(ElwhaMinTemp, ElwhaMaxTemp, ElwhaMedianTemp, ncol = 1, top = textGrob("Elwha River Temperature Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

DungenessTemperature <- grid.arrange(DungenessMinTemp, DungenessMaxTemp, DungenessMedianTemp, ncol = 1, top = textGrob("Dungeness River Temperature Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

#stacking these with salmon graphs

SkokomishTrendsTemp <- grid.arrange(SkokomishReturns, SkokomishMinTemp, SkokomishMaxTemp, SkokomishMedianTemp, ncol = 1, top = textGrob("Skokomish Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

DungenessTrendsTemp <- grid.arrange(DungenessReturns, DungenessMinTemp, DungenessMaxTemp, DungenessMedianTemp, ncol = 1, top = textGrob("Dungeness Analysis", gp = gpar(fontsize = 16, fontface = "bold")))

ElwhaTrendsTemp <- grid.arrange(ElwhaReturns, ElwhaMinTemp, ElwhaMaxTemp, ElwhaMedianTemp, ncol = 1, top = textGrob("Elwha Analysis", gp = gpar(fontsize = 16, fontface = "bold")))
```


```{r}
# Creating a variety of linear regression models to analyze our data and determine potential trends between salmon returns and climate variables. 

#
fish_lr <-
  aligned_data_stats %>%
  group_by(site_name) %>%
  group_map(~ lm(abundance_qty ~ Flow_max, data = .))

fish_lr_summ <-
  lapply(fish_lr, summary) 

names(fish_lr_summ) <- c("Dunguness River", "Elwha River", "Skokomish River")

fish_pvals <-
  lapply(fish_lr_summ, function(s) {
  coef(s)[,4]
})

```


```{r}
#Creating linear regression plots


#With equation displayed
aligned_data_stats %>%
  ggplot(aes(x = prcp_max, y = abundance_qty, color = site_name)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_poly_eq(aes(label = paste(after_stat(eq.label), ..rr.label.., sep = "~~")), formula = y ~x, parse = TRUE, size = 3) +
  facet_wrap(facet = "site_name", nrow = 3, scale = "free") +
  labs(
 color = "site name",
 x = "Max Annual Precipitation (mm)",
 y = "Salmon Return Abundance"
 ) +
 theme_minimal() +
 theme(
 legend.position = "bottom"
 ) 

#without equation displayed
aligned_data_stats %>%
 ggplot(aes(x = Flow_max, y = abundance_qty, color = site_name)) +
 geom_point() +
 geom_smooth(method = "lm") +
 facet_wrap(facet = "site_name", nrow = 3, scale = "free") + 
 labs(
 color = "site name",
 x = "Max Annual Discharge (cfs)",
 y = "Salmon Return Abundance"
 ) +
 theme_minimal() +
 theme(
 legend.position = "bottom"
 ) 

#with equation displayed
aligned_data_stats %>%
 ggplot(aes(x = Flow_max, y = abundance_qty, color = site_name)) +
 geom_point() +
 geom_smooth(method = "lm") +
  stat_poly_eq(aes(label = paste(after_stat(eq.label), ..rr.label.., sep = "~~")), formula = y ~x, parse = TRUE, size = 3) +
 facet_wrap(facet = "site_name", nrow = 3, scale = "free") + 
 labs(
 color = "site name",
 x = "Max Annual Discharge (cfs)",
 y = "Salmon Return Abundance"
 ) +
 theme_minimal() +
 theme(
 legend.position = "bottom"
 ) 


#with equation displayed
aligned_data_stats %>%
  ggplot(aes(x = Flow_min, y = abundance_qty, color = site_name)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_poly_eq(aes(label = paste(after_stat(eq.label), ..rr.label.., sep = "~~")), formula = y ~x, parse = TRUE, size = 3) +
  facet_wrap(facet = "site_name", nrow = 3, scale = "free") + 
  labs(
 color = "site name",
 x = "Minimum Annual Discharge (cfs)",
 y = "Salmon Return Abundance"
 ) +
 theme_minimal() +
 theme(
 legend.position = "bottom"
 )

#with equation displayed
aligned_data_stats %>%
  ggplot(aes(x = t_ann_min, y = abundance_qty, color = site_name)) +
  geom_point() +
   geom_smooth() +
  stat_poly_eq(aes(label = paste(after_stat(eq.label), ..rr.label.., sep = "~~")), formula = y ~x, parse = TRUE, size = 3) +
  facet_wrap(facet = "site_name", nrow = 3, scale = "free") + 
  labs(
 color = "site name",
 x = "Annual Minimum Temperature (C)",
 y = "Salmon Return Abundance"
 ) +
 theme_minimal() +
 theme(
 legend.position = "bottom"
 )

#with equation displayed
aligned_data_stats %>%
  ggplot(aes(x = t_ann_max, y = abundance_qty, color = site_name)) +
  geom_point() +
  geom_smooth(method = "lm") +
  stat_poly_eq(aes(label = paste(after_stat(eq.label), ..rr.label.., sep = "~~")), formula = y ~x, parse = TRUE, size = 3) +
  facet_wrap(facet = "site_name", nrow = 3, scale = "free") + 
  labs(
 color = "site name",
 x = "Annual Max Temperature (C)",
 y = "Salmon Return Abundance"
 ) +
 theme_minimal() +
 theme(
 legend.position = "bottom"
 )

```


```{r}
# Creating the returns v max cfs plot with an attempt at fixing positions


#attempt to resolve eq plotting issues
aligned_data_stats_reg <- aligned_data_stats %>%
  group_by(site_name) %>%
  mutate(
    label.x = min(t_ann_min) + 0.05 * (max(t_ann_min) - min(t_ann_min)),
    label.y = max(abundance_qty) - 0.05 * (max(abundance_qty) - min(abundance_qty))
  )


# This one actually makes the good plot
aligned_data_stats_reg %>%
  ggplot(aes(x = Flow_max, y = abundance_qty, color = site_name)) +
  geom_point() +
  facet_wrap(~site_name, nrow = 3, scales = "free") +
  geom_smooth(method = "lm") +
  stat_regline_equation(
    aes(label.x = label.x, label.y = label.y,
        label = paste(..eq.label.., ..rr.label.., sep = "~~~")),
    size = 4,
    hjust = 0
  ) +
  labs(
    x = "Maximum Flow (cfs)",
    y = "Abundance Quantity"
  ) +
  theme(legend.position="none")


```



```{r}

# Leaded data for fish. this is wrong, but we left the code in as we presented on it and wanted it to be viewable

gage_fish_lead <-
  gage_fish_all %>%
  group_by(site_name) %>%
  mutate(abundance_lead = lead(abundance_qty, 365*4),
         Date_lead = Date + years(4),
         ann_lead = year(Date_lead)
         )

# Create a dungeness subset for efficient testing
Dungeness_data <-
  gage_fish_lead %>%
  filter(site_name == "Dungeness_River")




# uses some temp columns to create filtered data. 
# filtered dates are based on arbitrarily generated Julian days, so changing the range first requires figuring out the corresponding Julian days.
#this one works but only on Dungeness
dungeness_julian <- 
  Dungeness_data %>%
  filter(ann_lead != 1986, ann_lead != 2027) %>%   #remove these rows bc theyre less than 365 days and that breaks things
  group_by(ann_lead) %>%
  mutate(fake_dates = seq(ymd('1970-01-01'),
                          ymd('1970-12-31'), 
                          by = '1 day'),
         fake_julian = julian(fake_dates, origin = as.Date("1970-01-01"))
  ) %>%
  filter(!(between(fake_julian, 151, 211))) %>%
  bind_rows(                                    #re-add the earlier filtered rows 
    (filter(
      Dungeness_data, year(Date_lead) < 1987)
    ),
    .) %>%
  bind_rows(
    (filter(
      Dungeness_data, year(Date_lead) > 2026)
    ),
    .) %>%
  arrange(Date_lead)



# attempting to do it to all sites
gage_fish_lead_filt <-
  gage_fish_lead %>%
  group_by(site_name) %>%
  filter(ann_lead != 1986, ann_lead != 2027) %>%   #remove these rows bc they're less than 365 days and that breaks things
  group_by(ann_lead) %>%
  mutate(fake_dates = seq(ymd('1970-01-01'),
                          ymd('1970-12-31'), 
                          by = '1 day'),
         fake_julian = julian(fake_dates, origin = as.Date("1970-01-01"))
  ) %>%
  filter(!(between(fake_julian, 151, 211))) %>%
  bind_rows(                                    #re-add the earlier filtered rows 
    (filter(
      gage_fish_lead, year(Date_lead) < 1987)
    ),
    .) %>%
  bind_rows(
    (filter(
      gage_fish_lead, year(Date_lead) > 2026)
    ),
    .) %>%
  arrange(Date_lead)


# create it as a function and lapply it?

migration_filter <-
  function(f) {
    f %>%
      filter(ann_lead != 1986, ann_lead != 2027) %>%   #remove these rows bc theyre less than 365 days and that breaks things
      group_by(ann_lead) %>%
      mutate(fake_dates = seq(ymd('1970-01-01'),
                              ymd('1970-12-31'), 
                              by = '1 day'),
             fake_julian = julian(fake_dates, origin = as.Date("1970-01-01"))
      ) %>%
      filter(!(between(fake_julian, 151, 211))) %>%
      bind_rows(                                    #re-add the earlier filtered rows 
        (filter(
          f, 
          year(Date_lead) < 1987)),
        .) %>%
      bind_rows(
        filter(
          f, 
          between(Date_lead, ymd("2027-01-01"), ymd("2027-05-31")) |
          ymd(Date_lead) > ymd("2027-07-31")),
        .) %>%
      arrange(Date_lead)
  }

gage_fish_lead %>%
  filter(site_name == "Skokomish_River") %>%
  migration_filter() %>%
  view()

gage_fish_lead %>%
  group_by(site_name) %>%
  group_map(~ migration_filter(.x))

```


```{r}
# Visualizing Skokomish flow codes

gage_fish_all %>%
  filter(site_name == "Skokomish_River") %>%
  ggplot(aes(x = Date, y = Flow, color = Flow_cd)) +
  geom_point() +
  labs(
    color = "Flow Code",
    x = "Year",
    y = "Flow (cfs)",
    title = "Skokomish River" 
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom", 
    plot.title = element_text(hjust = 0.5)
  ) +
  theme()

ggsave("skoko_cd code.jpeg")

```


#Linear Regression with r^2 and regression eq

```{r}
anim_fish_all_df <- gage_fish_all %>%
  mutate(
    year = year(Date),
    month_day = as.Date(format(Date, "2000-%m-%d")),  # Rebase all dates to year 2000
    title_clean = gsub("_", " ", site_name)
  )


flow_anim <- ggplot(df, aes(x = month_day, y = Flow, color = title_clean)) +
  geom_line() +
  scale_x_date(date_breaks = "1 month", date_labels = "%b", limits = as.Date(c("2000-01-01", "2000-12-31"))) +
  theme_minimal() +
  labs(title = "Year: {current_frame}",
       x = "Month",
       color = "Site name") +
  transition_manual(year)

animate(flow_anim, width = 800, height = 400, fps = 5)

```

